### ISSUE TITLE
module stopped working. canihazip.com domain has been taken over by someone else

### ISSUE THREAD

**Issue by LarsBuur** [markogresak/canihazip#2]
check

http://canihazip.com/

**Comment by markogresak** [comment]
Thanks for pointing it out. 

To be honest, I have stopped paying attention to this project a while ago. 

I suggest using a more popular and better maintained project [`public-ip`](https://www.npmjs.com/package/public-ip). 

I will update the readme to include this information and deprecate the package.

**Comment by LarsBuur** [comment]
Thank you for your reply. I have not used it as well for a while -but some old solution suddenly fell on it´s back and this was the culprit.

**Comment by markogresak** [comment]
@LarsBuur I'm sorry that this package caused problems. I understand the frustration, it's usually not easy to debug when something in node_modules broke because you expect it to work.

I have released [v1.0.3](https://github.com/markogresak/canihazip/releases/tag/v1.0.3) to use [ipify.org](https://www.ipify.org/) as a fallback, so this package should now work for any `^1.0.x` version. 

But as said in my previous comment, I am not maintaining this package, so I have added a deprecation notice and suggestion to use [`public-ip`](https://www.npmjs.com/package/public-ip), published with [v1.0.4](https://github.com/markogresak/canihazip/releases/tag/v1.0.4).

**Comment by programmeruser2** [comment]
To anyone reading this, https://icanhazip.com/ is maintained by Cloudflare and works pretty similarly to the old website

**Comment by markogresak** [comment]
> https://icanhazip.com/ is maintained by Cloudflare and works pretty similarly

Yes, and the recommended `public-ip` package uses this url to resolve the ip.
